#!/usr/bin/python3
import tkinter as tk
import tkinter.ttk as ttk
from tkcalendar import Calendar
import datetime as dt

class UpdateWindow(tk.Toplevel):
    def __init__(self, master=None, **kw):
        super(UpdateWindow, self).__init__(master, **kw)
        frame2 = ttk.Frame(self)
        frame2.configure(height=200, width=200)
        label4 = ttk.Label(frame2)
        label4.configure(text='warehouse_uid')
        label4.pack(fill="x", side="left")
        self.wareEntry = ttk.Entry(frame2)
        self.wareEntry.pack(expand="true", fill="x", side="left")
        frame2.pack(expand="true", fill="both", side="top")
        frame3 = ttk.Frame(self)
        frame3.configure(height=200, width=200)
        label5 = ttk.Label(frame3)
        label5.configure(text='store_uid')
        label5.pack(fill="x", side="left")
        self.storeEntry = ttk.Entry(frame3)
        self.storeEntry.pack(expand="true", fill="x", side="left")
        frame3.pack(expand="true", fill="both", side="top")
        frame4 = ttk.Frame(self)
        frame4.configure(height=200, width=200)
        label6 = ttk.Label(frame4)
        label6.configure(text='product_uid')
        label6.pack(fill="x", side="left")
        self.productEntry = ttk.Entry(frame4)
        self.productEntry.pack(expand="true", fill="x", side="left")
        frame4.pack(expand="true", fill="both", side="top")
        frame5 = ttk.Frame(self)
        frame5.configure(height=200, width=200)
        label7 = ttk.Label(frame5)
        label7.configure(text='shipper_uid')
        label7.pack(fill="x", side="left")
        self.shipperEntry = ttk.Entry(frame5)
        self.shipperEntry.pack(expand="true", fill="x", side="left")
        frame5.pack(expand="true", fill="both", side="top")
        frame6 = ttk.Frame(self)
        frame6.configure(height=200, width=200)
        label8 = ttk.Label(frame6)
        label8.configure(text='current')
        label8.pack(fill="x", side="left")
        self.currentEntry = ttk.Entry(frame6)
        self.currentEntry.pack(expand="true", fill="x", side="left")
        frame6.pack(expand="true", fill="both", side="top")
        frame7 = ttk.Frame(self)
        frame7.configure(height=200, width=200)
        label9 = ttk.Label(frame7)
        label9.configure(text='update')
        label9.pack(fill="x", side="left")
        self.updateEntry = ttk.Entry(frame7)
        self.updateEntry.pack(expand="true", fill="x", side="left")
        frame7.pack(expand="true", fill="both", side="top")
        frame8 = ttk.Frame(self)
        frame8.configure(height=200, width=200)
        label10 = ttk.Label(frame8)
        label10.configure(text='cost')
        label10.pack(fill="x", side="left")
        self.costEntry = ttk.Entry(frame8)
        self.costEntry.pack(expand="true", fill="x", side="left")
        frame8.pack(expand="true", fill="both", side="top")
        frame9 = ttk.Frame(self)
        frame9.configure(height=200, width=200)
        label11 = ttk.Label(frame9)
        label11.configure(text='arrived')
        label11.pack(fill="x", side="left")
        self.arrivedLabel = ttk.Label(frame9)
        self.arrivedLabel.pack(expand="true", fill="x", side="left")
        self.arrivedButton = ttk.Button(frame9)
        self.arrivedButton.configure(text='選擇')
        self.arrivedButton.pack(side="top")
        frame9.pack(expand="true", fill="both", side="top")
        frame10 = ttk.Frame(self)
        frame10.configure(height=200, width=200)
        label12 = ttk.Label(frame10)
        label12.configure(text='set off')
        label12.pack(fill="x", side="left")
        self.setOffLabel = ttk.Label(frame10)
        self.setOffLabel.pack(expand="true", fill="x", side="left")
        self.setOffButton = ttk.Button(frame10)
        self.setOffButton.configure(text='選擇')
        self.setOffButton.pack(side="top")
        frame10.pack(expand="true", fill="both", side="top")
        frame11 = ttk.Frame(self)
        frame11.configure(height=200, width=200)
        self.summitButton = ttk.Button(frame11)
        self.summitButton.configure(text='提交')
        self.summitButton.pack(expand="true", fill="x", side="left")
        self.cancelButton = ttk.Button(frame11)
        self.cancelButton.configure(text='取消')
        self.cancelButton.pack(expand="true", fill="x", side="left")
        frame11.pack(expand="true", fill="both", side="top")
        self.configure(height=400, width=400)

class DatePicker(tk.Toplevel):
    def __init__(self, master = None, 
                year: int = dt.datetime.today().year,
                month: int = dt.datetime.today().month,
                day: int = dt.datetime.today().day):
        
        super().__init__(master)
        self.calendar = Calendar(self, year = year, month = month, day = day)
        self.calendar.pack(expand = True, fill = "both")