# Form implementation generated from reading ui file 'customer.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import store

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        def searchStore():
            region = self.comboBox.currentText()
            stores = store.getStoreInfo(region)
            self.comboBox_2.clear()
            for s in stores:
                self.comboBox_2.addItem(s[1])
        def searchStoreStock():
            selectedStoreName = self.comboBox_2.currentText()
            selectedStoreUid = store.findStoreUid(selectedStoreName)
            storeStock = store.getStoreStock(selectedStoreUid)
            self.textBrowser.clear()
            self.textBrowser.append("%s 目前存貨:" % selectedStoreName)
            
            for s in storeStock:
                self.textBrowser.append("%s: 剩餘數量 %s" % (s[1], s[2]))
        
        
        mainWindow.resize(340, 470)
        self.centralwidget = QtWidgets.QWidget(parent=mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 58, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 58, 15))
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(100, 30, 80, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.addItems(["高雄", "台南"])
        self.comboBox_2.setGeometry(QtCore.QRect(100, 60, 80, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(30, 100, 291, 341))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(220, 30, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 60, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)
        self.pushButton.clicked.connect(searchStore)
        self.pushButton_2.clicked.connect(searchStoreStock)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.label.setText(_translate("mainWindow", "縣市"))
        self.label_2.setText(_translate("mainWindow", "店名"))
        self.pushButton.setText(_translate("mainWindow", "查詢店名"))
        self.pushButton_2.setText(_translate("mainWindow", "查詢存貨"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.setWindowTitle("客戶端查詢店名與存貨")
    mainWindow.show()
    sys.exit(app.exec())
